# Rust formatting configuration for gitk-rs
# See https://rust-lang.github.io/rustfmt for configuration options

# Edition to use (2024 edition)
edition = "2024"

# Maximum line width
max_width = 100

# Hard tab width
hard_tabs = false
tab_spaces = 4

# Line ending style
newline_style = "Unix"

# Use small heuristics
use_small_heuristics = "Default"

# Remove extra newlines
remove_nested_parens = true

# Function definitions
fn_params_layout = "Tall"

# Keep stable formatting options only

# Imports
reorder_imports = true

# Expressions
force_explicit_abi = true

# 2024 edition allows more stable formatting options
# Note: Some options may still require nightly, but 2024 edition enables more